/*
 * MainUI.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import XML.*;
import entnetclient.EntNetClient;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;

import javax.swing.ListSelectionModel;

/**
 *
 * @author  __USER__
 */
public class MainUI extends javax.swing.JFrame {
    private EntNetClient controller;
	/** Creates new form MainUI */
	public MainUI(EntNetClient ec) {
		initComponents();
                controller = ec;
	}

        public void populateInitScreen(){
            
            //XMLRequest friendNameListinXMLReq = xmlr_arr.get(0);
            //System.out.println("FROM MainUI, printing friendList: "+friendNameListinXMLReq.getRequestDetail());
 
        }
        
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Region1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        re1 = new javax.swing.JLabel();
        re1b = new javax.swing.JLabel();
        re1a = new javax.swing.JLabel();
        Region1_Name = new javax.swing.JLabel();
        Region1_Phone = new javax.swing.JLabel();
        Region4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        re4 = new javax.swing.JLabel();
        Region2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        re2 = new javax.swing.JLabel();
        Region5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        re5 = new javax.swing.JLabel();
        Region3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        re3 = new javax.swing.JLabel();
        Region6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        re6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Region1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("Region1");

        re1.setText("Personal Info");

        re1b.setText("Phone:");

        re1a.setText("Name:");

        Region1_Name.setText("jLabel7");

        Region1_Phone.setText("jLabel7");

        javax.swing.GroupLayout Region1Layout = new javax.swing.GroupLayout(Region1);
        Region1.setLayout(Region1Layout);
        Region1Layout.setHorizontalGroup(
            Region1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Region1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Region1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(re1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(Region1Layout.createSequentialGroup()
                        .addComponent(re1b)
                        .addGap(18, 18, 18)
                        .addComponent(Region1_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Region1Layout.createSequentialGroup()
                        .addComponent(re1a)
                        .addGap(18, 18, 18)
                        .addComponent(Region1_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        Region1Layout.setVerticalGroup(
            Region1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Region1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(re1)
                .addGap(7, 7, 7)
                .addGroup(Region1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(re1a)
                    .addComponent(Region1_Name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Region1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(re1b)
                    .addComponent(Region1_Phone))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        Region4.setBackground(new java.awt.Color(204, 255, 204));

        jLabel4.setText("Region4");

        re4.setText("Company Announcement Board");

        javax.swing.GroupLayout Region4Layout = new javax.swing.GroupLayout(Region4);
        Region4.setLayout(Region4Layout);
        Region4Layout.setHorizontalGroup(
            Region4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Region4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Region4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(re4)
                    .addComponent(jLabel4))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        Region4Layout.setVerticalGroup(
            Region4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Region4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(re4)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        Region2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setText("Region2");

        re2.setText("Current Location");

        javax.swing.GroupLayout Region2Layout = new javax.swing.GroupLayout(Region2);
        Region2.setLayout(Region2Layout);
        Region2Layout.setHorizontalGroup(
            Region2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Region2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Region2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(re2)
                    .addComponent(jLabel2))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        Region2Layout.setVerticalGroup(
            Region2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Region2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(re2)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        Region5.setBackground(new java.awt.Color(204, 255, 204));

        jLabel5.setText("Region5");

        re5.setText("Department Discussion Board");

        javax.swing.GroupLayout Region5Layout = new javax.swing.GroupLayout(Region5);
        Region5.setLayout(Region5Layout);
        Region5Layout.setHorizontalGroup(
            Region5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Region5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Region5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(re5)
                    .addComponent(jLabel5))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        Region5Layout.setVerticalGroup(
            Region5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Region5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(re5)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        Region3.setBackground(new java.awt.Color(204, 255, 204));

        jLabel3.setText("Region3");

        re3.setText("Currently working on project");

        javax.swing.GroupLayout Region3Layout = new javax.swing.GroupLayout(Region3);
        Region3.setLayout(Region3Layout);
        Region3Layout.setHorizontalGroup(
            Region3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Region3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Region3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(re3)
                    .addComponent(jLabel3))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        Region3Layout.setVerticalGroup(
            Region3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Region3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(re3)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        Region6.setBackground(new java.awt.Color(204, 255, 204));

        jLabel6.setText("Region6");

        re6.setText("Personal Message board");

        javax.swing.GroupLayout Region6Layout = new javax.swing.GroupLayout(Region6);
        Region6.setLayout(Region6Layout);
        Region6Layout.setHorizontalGroup(
            Region6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Region6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Region6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(re6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        Region6Layout.setVerticalGroup(
            Region6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Region6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(re6)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            
            
            
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
    	jList1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
  		 MouseListener   mouseListener   =   new   MouseAdapter()   { 
  	          public   void   mouseClicked(MouseEvent   e)   { 
  	                          int   index   =   jList1.locationToIndex(e.getPoint()); 
  	                          System.out.println( "Double   clicked   on   Item   "   +   index); 
							  try{
								controller.clientViewOtherPersonBoard("chen"); //just a test. will need index's user id string as input
							  }
							  catch(Exception mye){System.err.println("jList error!");};
  	                    
  	          } 
  	  }; 
  	  jList1.addMouseListener(mouseListener);
        jList1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jList1InputMethodTextChanged(evt);
            }
        });
        jList1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jList1PropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Region1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Region3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Region2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Region6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Region5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Region4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Region1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Region4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(249, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Region2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Region5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Region6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Region3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void jList1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jList1PropertyChange
            // TODO add your handling code here:
        }//GEN-LAST:event_jList1PropertyChange

        private void jList1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jList1InputMethodTextChanged
            // TODO add your handling code here:
        }//GEN-LAST:event_jList1InputMethodTextChanged

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            try{
                
            }
            catch(Exception e){
                
            }
        }//GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args the command line arguments
	 */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Region1;
    private javax.swing.JLabel Region1_Name;
    private javax.swing.JLabel Region1_Phone;
    private javax.swing.JPanel Region2;
    private javax.swing.JPanel Region3;
    private javax.swing.JPanel Region4;
    private javax.swing.JPanel Region5;
    private javax.swing.JPanel Region6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel re1;
    private javax.swing.JLabel re1a;
    private javax.swing.JLabel re1b;
    private javax.swing.JLabel re2;
    private javax.swing.JLabel re3;
    private javax.swing.JLabel re4;
    private javax.swing.JLabel re5;
    private javax.swing.JLabel re6;
    // End of variables declaration//GEN-END:variables

}