/*
 * UI.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.io.IOException;
import java.io.PrintWriter;

import javax.swing.JOptionPane;

import entnetclient.*;

/**
 *
 * @author  Shuai
 */
public class LoginUI extends javax.swing.JFrame {
	/**
	 * 
	 */
	//private static final long serialVersionUID = 1L;
	//public static PrintWriter out;
	public static EntNetClient controller;

	/** Creates new form UI */
	public LoginUI(EntNetClient ec) {
		initComponents();

		controller = ec;

		//controller = EntNetClient.getInstance();
		//clientMainThread = controller.getClientMainThreadHandler();
		//controller.startClientMainThread();

	}

	/*
	public static void main(String[] args) {
	java.awt.EventQueue.invokeLater(new Runnable() {
		public void run() {
			new LoginUI().setVisible(true);
		}
	});
	}*/

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jButtonLogin = new javax.swing.JButton();
		jButtonReg = new javax.swing.JButton();
		jLabelId = new javax.swing.JLabel();
		jLabelPwd = new javax.swing.JLabel();
		jLabelRegid = new javax.swing.JLabel();
		jLabelRegpwd = new javax.swing.JLabel();
		jLabelRegcontact = new javax.swing.JLabel();
		jTextFieldId = new javax.swing.JTextField();
		jTextFieldPwd = new javax.swing.JTextField();
		jTextFieldRegid = new javax.swing.JTextField();
		jTextFieldRegpwd = new javax.swing.JTextField();
		jTextFieldRegcontact = new javax.swing.JTextField();
		jLabelRegrole = new javax.swing.JLabel();
		jTextFieldRegrole = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jButtonLogin.setText("Login");
		jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonLoginActionPerformed(evt);
			}
		});

		jButtonReg.setText("Regist");
		jButtonReg.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonRegActionPerformed(evt);
			}
		});

		jLabelId.setText("User Id");

		jLabelPwd.setText("Password");

		jLabelRegid.setText("RegID");

		jLabelRegpwd.setText("Regpassword");

		jLabelRegcontact.setText("Regcontact");

		jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldIdActionPerformed(evt);
			}
		});

		jTextFieldRegpwd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldRegpwdActionPerformed(evt);
			}
		});

		jLabelRegrole.setText("Regrole");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(97, 97,
																		97)
																.addComponent(
																		jButtonLogin)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		280,
																		Short.MAX_VALUE)
																.addComponent(
																		jButtonReg))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(53, 53,
																		53)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabelId)
																								.addGap(19,
																										19,
																										19))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabelPwd)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																				.addComponent(
																						jTextFieldPwd,
																						javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jTextFieldId,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						86,
																						Short.MAX_VALUE))
																.addGap(90, 90,
																		90)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabelRegid)
																				.addComponent(
																						jLabelRegpwd)
																				.addComponent(
																						jLabelRegcontact)
																				.addComponent(
																						jLabelRegrole))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		57,
																		Short.MAX_VALUE)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jTextFieldRegrole)
																				.addComponent(
																						jTextFieldRegcontact)
																				.addComponent(
																						jTextFieldRegpwd)
																				.addComponent(
																						jTextFieldRegid,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						94,
																						Short.MAX_VALUE))))
								.addGap(87, 87, 87)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGap(57, 57, 57)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabelId)
																				.addComponent(
																						jTextFieldId,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jTextFieldPwd,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabelPwd)))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabelRegid)
																				.addComponent(
																						jTextFieldRegid,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabelRegpwd)
																				.addComponent(
																						jTextFieldRegpwd,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jTextFieldRegcontact,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabelRegcontact))))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jTextFieldRegrole,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		132,
																		Short.MAX_VALUE)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jButtonLogin)
																				.addComponent(
																						jButtonReg))
																.addGap(55, 55,
																		55))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabelRegrole)
																.addContainerGap()))));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jTextFieldRegpwdActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButtonRegActionPerformed(java.awt.event.ActionEvent evt) {
		if(jTextFieldRegid.getText().equals("")||jTextFieldRegrole.getText().equals("")||jTextFieldRegpwd.getText().equals("")||jTextFieldRegcontact.getText().equals(""))
			JOptionPane.showMessageDialog(null, "Please fill in all the four reg sections!");
		else{
		controller.clientRegist(
				jTextFieldRegid.getText(), jTextFieldRegpwd.getText(),
				jTextFieldRegcontact.getText(),
				jTextFieldRegrole.getText());}
		
	}

	private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {

		try {
			//System.out.println(">>>>>");
			controller.clientLogin(jTextFieldId.getText(),
					jTextFieldPwd.getText());

		} catch (Exception e) {
			e.printStackTrace();
		}
		;

	}

	private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	public static void checkRegist(Boolean b) {
		if (b == false)
			JOptionPane.showMessageDialog(null, "Registration failed!");
		else
			JOptionPane.showMessageDialog(null,
					"Registration succeed, please login!");
	}

	/**
	 * @param args the command line arguments
	 */

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButtonLogin;
	private javax.swing.JButton jButtonReg;
	private javax.swing.JLabel jLabelId;
	private javax.swing.JLabel jLabelPwd;
	private javax.swing.JLabel jLabelRegcontact;
	private javax.swing.JLabel jLabelRegid;
	private javax.swing.JLabel jLabelRegpwd;
	private javax.swing.JLabel jLabelRegrole;
	private javax.swing.JTextField jTextFieldId;
	private javax.swing.JTextField jTextFieldPwd;
	private javax.swing.JTextField jTextFieldRegcontact;
	private javax.swing.JTextField jTextFieldRegid;
	private javax.swing.JTextField jTextFieldRegpwd;
	private javax.swing.JTextField jTextFieldRegrole;
	// End of variables declaration//GEN-END:variables

}